<template lang="html">
  <div class="">
    <div class="terms">
      <h2>Apresentação e definições</h2>

        <p>Este site é de propriedade, mantido, e operado por [NOME DA SUA EMPRESA AQUI], com endereço na [ENDEREÇO COMPLETO AQUI], inscrita no CNPJ/MF sob o n.[CNPJ AQUI], com Inscrição Estadual nº [INSCRICAO AQUI] e endereço de e-mail [E-MAIL AQUI]. Este documento relaciona os termos e condições que devem ser observados pela [NOME DA SUA EMPRESA AQUI] e pelos Usuários (conforme definição abaixo) na utilização do Site, de suas ferramentas e de suas funcionalidades. A [NOME DA SUA EMPRESA AQUI] faculta acesso e utilização do Site a quaisquer Usuários. O Usuário declara ter lido e aceito estes Termos e Condições de Uso e das Políticas antes de ter iniciado a utilização do Site. Caso o Usuário não aceite estes Termos e Condições de Uso, não lhe será permitido acesso a áreas restritas do Site. Para os fins destes Termos e Condições de Uso, bem como das Políticas, os termos abaixo terão os seguintes significados: CALM. Central de Atendimento [NOME DA SUA EMPRESA AQUI] é o serviço de atendimento ao consumidor disponibilizado pela [NOME DA SUA EMPRESA AQUI] por meio de diversos canais de comunicação, indicados em cada uma das Políticas e no item 18 destes Termos e Condições de Uso;
        Clientes. Usuários que preencheram o cadastro e detêm uma Conta de Acesso;
        Compra. Transação por meio da qual um Cliente adquire um produto oferecido à venda no Site, mediante a realização de pagamento do valor do produto;
        Conta de Acesso. Credencial definida pelo nome de usuário (login) e senha de um visitante cadastrado (Cliente), pessoal e intransferível, que permite acesso à área restrita e às funcionalidades exclusivas no Site, tais como acesso e alteração de dados pessoais, inscrição e cancelamento de participação em cursos, criação, edição e
        remoção de listas de desejos, entre outras;
        [NOME DA SUA EMPRESA AQUI]. A [NOME DA SUA EMPRESA AQUI];
        Marca. Quaisquer sinais distintivos de titularidade da e/ou licenciados à [NOME DA SUA EMPRESA AQUI], que sejam utilizados na identificação do Site, de seu conteúdo ou de serviço prestado pela [NOME DA SUA EMPRESA AQUI]. Políticas. As políticas que complementam e integram estes Termos e Condições de Uso, nominalmente Política de Trocas e Devoluções, Política de Pagamentos, Política de Entrega de Produtos e a Política de Privacidade e Segurança, todas disponíveis no Site;
        Propriedade Intelectual da [NOME DA SUA EMPRESA AQUI]. Todos os bens de propriedade intelectual de titularidade da [NOME DA SUA EMPRESA AQUI], de qualquer empresa pertencente a seu grupo econômico, ou, ainda, de terceiro, cujo uso seja licenciado e/ou autorizado à [NOME DA SUA EMPRESA AQUI], incluindo mas não se limitando a Marcas, patentes, invenções ou modelos de utilidade, desenhos industriais, know-how, segredos de negócio, ilustrações, fotografias e/ou conteúdos de qualquer tela do Site ou quaisquer obras intelectuais ou outros conteúdos que estejam inseridos em qualquer obra intelectual ou qualquer bem protegido por direitos de propriedade intelectual. Site. O website de propriedade, mantido e operado por [NOME DA SUA EMPRESA AQUI], hospedado no domínio [leroymerlin.com.br] e todas as páginas nele compreendidas; e
        Usuários. Quaisquer pessoas que acessem o Site, incluindo visitantes anônimos e Clientes.</p>

      <h2>Regras de utilização do Site</h2>

         <p>O Usuário obriga-se a utilizar o Site respeitando e observando estes Termos e Condições de Uso, bem como a legislação vigente, os costumes e a ordem pública. Desta forma, o Usuário concorda que não poderá: (i) lesar direitos de terceiros, independentemente de sua natureza, em qualquer momento, inclusive no decorrer do uso do Site; (ii) executar atos que limitem ou impeçam o acesso e a utilização do Site, em condições adequadas, aos demais Usuários; (iii) acessar ilicitamente o Site ou sistemas informáticos de terceiros relacionados ao Site ou à [NOME DA SUA EMPRESA AQUI] sob qualquer meio ou forma; (iv) difundir programas ou vírus informáticos suscetíveis de causar danos de qualquer natureza, inclusive em equipamentos e sistemas da [NOME DA SUA EMPRESA AQUI] ou de terceiros; (v) utilizar mecanismos que não os expressamente habilitados ou recomendados no Site para obtenção de informações, conteúdos e serviços; (vi) realizar quaisquer atos que de alguma forma possam implicar qualquer prejuízo ou dano à [NOME DA SUA EMPRESA AQUI] ou a outros Usuários; (vii) acessar áreas de programação do Site, bases de dados ou qualquer outro conjunto de informações que escape às áreas públicas ou restritas do Site; (viii) realizar ou permitir engenharia reversa, traduzir, modificar, alterar a linguagem, compilar, decompilar, modificar, reproduzir, alugar, sublocar, divulgar, transmitir, distribuir, usar ou, de outra maneira, dispor do Site ou das ferramentas e funcionalidades nele disponibilizadas sob qualquer meio ou forma, inclusive de modo a violar direitos da [NOME DA SUA EMPRESA AQUI] (inclusive de Propriedade Intelectual da [NOME DA SUA EMPRESA AQUI]) e/ou de terceiros; (ix) praticar ou participar de qualquer ato que constitua uma violação de qualquer direito da [NOME DA SUA EMPRESA AQUI] (inclusive de Propriedade Intelectual da [NOME DA SUA EMPRESA AQUI]) ou de terceiros ou ainda de qualquer lei aplicável, ou agir sob qualquer meio ou forma que possa contribuir com
         tal violação; (x) interferir na segurança ou cometer usos indevidos contra o Site ou qualquer recurso do sistema, rede ou serviço conectado ou que possa ser acessado por meio do Site, devendo acessar o Site apenas para fins lícitos e autorizados; (xi) utilizar o domínio da [NOME DA SUA EMPRESA AQUI] para criar links ou atalhos a serem disponibilizados em e-mails não solicitados (mensagens spam) ou em websites de terceiros ou do próprio Usuário ou, ainda, para realizar qualquer tipo de ação que possa vir a prejudicar a [NOME DA SUA EMPRESA AQUI] ou terceiros; (xii) utilizar aplicativos automatizados de coleta e seleção de dados para realizar operações massificadas ou para quaisquer finalidades ou, ainda, para coletar e transferir quaisquer dados que possam ser extraídos do Site para fins não permitidos ou ilícitos, (xiii) utilizar as ferramentas e funcionalidades do Site para difundir mensagens não relacionadas com o Site ou com as finalidades do Site, incluindo mensagens de cunho racista, étnico, político, religioso, cultural ou depreciativo, difamatório e/ou calunioso de qualquer pessoa ou grupo social. O Usuário concorda em indenizar, defender e isentar a [NOME DA SUA EMPRESA AQUI] de qualquer reclamação, notificação, intimação ou ação judicial ou extrajudicial, ou ainda de qualquer responsabilidade, dano, custo ou despesa decorrente de qualquer violação e/ou infração cometida pelo Usuário ou qualquer pessoa agindo em seu nome, com seu consentimento ou tolerância, em relação ao Site (inclusive com relação a qualquer disposição destes Termos e Condições de Uso), inclusive qualquer pessoa que tenha obtido os dados do Usuário relacionados a sua Conta de Acesso ou a sua navegação no Site. A [NOME DA SUA EMPRESA AQUI] poderá, a seu exclusivo critério, bloquear, restringir, desabilitar ou impedir o acesso de qualquer Usuário ao Site, total ou parcialmente, sem qualquer aviso prévio, sempre que for detectada uma conduta inadequada do Usuário, sem prejuízo das medidas administrativas, extrajudiciais e judiciais que julgar convenientes.</p>
     </div>

     <div class="buttons">
       <button class="button is-primary">Aceitar</button>
       <button class="button is-info">Cancelar</button>
     </div>

  </div>
</template>

<script>
export default {
  name: 'TermService'
}
</script>

<style lang="scss" scoped>
  .buttons { margin-top: 50px; text-align: right; }
</style>
